services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_livraria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 132903

      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  db-data: